'''student={
    "name":"sadhana",
    "age":"22",
    "course":"cse"
}
print(student["name"])
print(student["age"])
print(student["course"])
'''

'''student={
    "name":"sadhana",
    "age":"22",
    "course":"cse"
}
print(student)
'''

student={
    "name":"sadhana",
    "age":"22",
    "course":"cse"
}
print(student)
student.update({"age":23})
print(student)
student.pop("name")
print(student)
student.popitem()
print(student)